FROM node:latest as builder

WORKDIR /app

COPY ./package.json ./package-lock.json ./

RUN npm install

COPY ./tsconfig.json ./
COPY ./src ./src
COPY ./public ./public
COPY ./.env.kathmandunet ./.env.kathmandunet

RUN npm run build:kathmandunet

FROM nginx:latest

COPY --from=builder /app/build /usr/share/nginx/html
