FROM node:18-alpine as builder

WORKDIR /app

# ENV ENV=ghostnet

COPY ./package.json ./

RUN npm install

COPY ./tsconfig.json ./jsconfig.json ./
COPY ./pages ./pages
COPY ./src ./src
COPY ./styles ./styles
COPY ./public ./public
COPY ./postcss.config.js ./postcss.config.js
COPY ./next.config.js ./next.config.js
COPY ./tailwind.config.js ./tailwind.config.js


RUN npm run build:ghostnet

EXPOSE 80

CMD ["npm", "run", "start:ghostnet"]

