FROM node:latest as builder

WORKDIR /app

COPY ./package.json  ./

RUN npm install

COPY ./tsconfig.json ./jsconfig.json ./
COPY ./src ./src
COPY ./public ./public
COPY ./img ./img
COPY ./config ./config
COPY ./.env.limanet ./.env.limanet

RUN npm run build:limanet-ci

FROM nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html
