FROM node:latest as builder

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY ./tsconfig.json ./jsconfig.json ./
COPY ./pages ./pages
COPY ./styles ./styles
COPY ./src ./src
COPY ./public ./public
COPY ./postcss.config.js ./postcss.config.js
COPY ./next.config.js ./next.config.js
COPY ./tailwind.config.js ./tailwind.config.js

RUN npm run build

EXPOSE 80

CMD ["npm", "start"]
