declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NEXT_PUBLIC_BATCHER_CONTRACT_HASH: string;
      NEXT_PUBLIC_MARKET_MAKER_CONTRACT_HASH: string;
      NEXT_PUBLIC_TOKEN_MANAGER_CONTRACT_HASH: string;
      NEXT_PUBLIC_TZBTC_VAULT_CONTRACT_HASH: string;
      NEXT_PUBLIC_USDT_VAULT_CONTRACT_HASH: string;
      NEXT_PUBLIC_EURL_VAULT_CONTRACT_HASH: string;
      NEXT_PUBLIC_USDTZ_VAULT_CONTRACT_HASH: string;
      NEXT_PUBLIC_BTCTZ_VAULT_CONTRACT_HASH: string;

      NEXT_PUBLIC_NETWORK_TARGET: string;
      NEXT_PUBLIC_BATCHER_URI: string;
      NEXT_PUBLIC_BATCHER_LOGO_PATH: string;
      NEXT_PUBLIC_TEZOS_NODE_URI: string;
      NEXT_PUBLIC_TZKT_API_URI: string;
      NEXT_PUBLIC_LOCAL_STORAGE_KEY_STATE: string;
      NEXT_PUBLIC_GA_TRACKING_ID: string;
    }
  }
}
export {};
