version: "3"

services:
  batcher-tick-ghostnet:
    container_name: tick-ghostnet
    build:
      context: .
      dockerfile: Dockerfile.tick.ghostnet
    restart: always
  batcher-tick-limanet:
    container_name: tick-limanet
    build:
      context: .
      dockerfile: Dockerfile.tick.limanet
    restart: always
