FROM oxheadalpha/flextesa:latest

RUN apk update &&\
    apk add bash &&\
    apk add curl &&\
    apk add jq &&\
    tezos-client --endpoint https://ghostnet.tezos.marigold.dev config update

WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/

CMD [ "/etc/run/sandbox.sh", "-u", "KT1H9hKtcqcMHuCoaisu8Qy7wutoUPFELcLm", "-t", "KT1XLyXAe5FWMHnoWa98xZqgDUyyRms2B3tG", "-b", "KT1Q94T4yntfYx2X2zVQTNuAtNbdppzFRRhE" ]
