version: "3"

volumes:
  client_data:
  node_data:

services:
  node:
    image: tezos/tezos:latest
    hostname: node
    command: tezos-node
    ports:
      - 9732:9732
    expose:
      - '8732'
    volumes:
      - node_data:/var/run/tezos/node
      - client_data:/var/run/tezos/client
    restart: on-failure