FROM oxheadalpha/flextesa:20221026

RUN apk update &&\
    apk add bash &&\
    apk add curl &&\
    apk add jq &&\

    octez-client --endpoint https://ghostnet.ecadinfra.com config update &&\
    octez-client import secret key oracle_account unencrypted:edskRzJUQ1xqCPkVXzT8EiUXjcCsXXkhpiHWE19fAV2JmqW68T6nVoXVPJyx99mjJzUa98NEeGr3kLcEh6NQGcpFKj7BoPRd88 --force

WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/

CMD [ "/etc/run/sandbox.sh", "-u", "KT1H9hKtcqcMHuCoaisu8Qy7wutoUPFELcLm", "-t", "KT1P8RdJ5MfHMK5phKJ5JsfNfask5v2b2NQS", "-b", "KT1D1Z7iAS7n1TDP9KpASCEMq2ExoJiHwYJE" ]