FROM oxheadalpha/flextesa:latest

RUN apk update &&\
    apk add bash &&\ 
    apk add curl &&\
    apk add jq &&\
    tezos-client --endpoint https://jakartanet.tezos.marigold.dev config update
    
WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/

CMD [ "/etc/run/sandbox.sh", "-u", "KT1AqXVEApbizK6ko4RqtCVdgw8CQd1xaLsF", "-t", "KT1XBUuCDb7ruPcLCpHz4vrh9jL9ogRFYTpr", "-b", "KT1CQw5Yo7cecCu496noAZDngeCUxhtHv5jC" ]