FROM oxheadalpha/flextesa:20221026

RUN apk update &&\
    apk add bash &&\
    apk add curl &&\
    apk add jq &&\
    octez-client --endpoint https://limanet.tezos.marigold.dev config update &&\
    octez-client import secret key oracle_account unencrypted:edskRheUgunCWW6m5JqoXBjRtxfWDdTjM557uC2TFeLDk4ThfJb5MUDbTagWq1aFjypoQbFjYBRZay1Ujpwg6c9rJcr7RBkBJS --force

WORKDIR /etc/run

COPY ./tick.sh /etc/run/

CMD [ "/etc/run/tick.sh", "-b", "KT1H8myUy1mVahUZcDXLHuP4ggsG5dt2BWHZ", "-f", "180" ]
