FROM oxheadalpha/flextesa:20221026

RUN apk update &&\
    apk add bash &&\
    apk add curl &&\
    apk add jq &&\
    octez-client --endpoint https://ghostnet.tezos.marigold.dev config update &&\
    octez-client import secret key oracle_account unencrypted:edskRzN27dotwLyiTyPbLUdPqMSVEubwxLBpvAfSduTZSEz7muXaHaMgN5GfVpvpMWo3Yh9pJyuoPPbReat9tQcuStrLJvEp7X --force

WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/


CMD [ "/etc/run/sandbox.sh", "-u", "KT1H9hKtcqcMHuCoaisu8Qy7wutoUPFELcLm", "-t", "KT1P8RdJ5MfHMK5phKJ5JsfNfask5v2b2NQS", "-b", "KT1PVXkKr5npJuaGeHE1TsD8sdsGcXqajnvJ" ]

