version: "3"

services:
  client: 
    container_name: batcher_client
    build: 
      context: .
      dockerfile: Dockerfile.price
    command: /etc/run/sandbox.sh
    volumes:
      - .:/etc/run
    restart: always
  