FROM oxheadalpha/flextesa:latest

RUN apk update && \
    apk add bash && \
    apk add curl && \
    apk add jq

RUN octez-client --endpoint https://ghostnet.tezos.marigold.dev config update && \
    octez-client import secret key oracle_account unencrypted:edskRzJUQ1xqCPkVXzT8EiUXjcCsXXkhpiHWE19fAV2JmqW68T6nVoXVPJyx99mjJzUa98NEeGr3kLcEh6NQGcpFKj7BoPRd88 --force

WORKDIR /etc/run

COPY ./tick.sh /etc/run/

CMD [ "/etc/run/tick.sh", "-b", "KT1JG7r23BFcc2GFdSnKBvijmagVzUncn9ry", "-m", "KT1VpMZjKtPa2oEdD2tQJiV7Mj3r4xY4QKFQ", "-f", "180" ]

