version: "3"

services:
  batcher-price-ghostnet:
    container_name: batcher-price-ghostnet
    build:
      context: .
      dockerfile: Dockerfile.price.ghostnet
    restart: always
  batcher-price-kathmandunet:
    container_name: batcher-price-kathmandunet
    build:
      context: .
      dockerfile: Dockerfile.price.kathmandunet
    restart: always
