FROM oxheadalpha/flextesa:latest

RUN apk update &&\
    apk add bash &&\
    apk add curl &&\
    apk add jq &&\
    tezos-client --endpoint https://kathmandunet.ecadinfra.com/ config update &&\
    tezos-client import secret key oracle_account unencrypted:edskRuYq76EQZ2hzmQpotWz8Fpnxdo2cCfP274tjxP4mJGR9LUGRSCfRWYRkEHJyBJLAkF56aPzuREGUsdtqXdYMAVLtpwbX7i --force

WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/

CMD [ "/etc/run/sandbox.sh", "-u", "KT1QVV45Rj9r6WbjLczoDxViP9s1JpiCsxVF", "-t", "KT1EGB9ZquErCN3dNvPurmNBuKCAi8pc1ce7", "-b", "KT1NVG4waVtLK8TXHMpFVK653YA4dDEnWYpz" ]
