FROM oxheadalpha/flextesa:20221026

RUN apk update &&\
    apk add bash &&\
    apk add curl &&\
    apk add jq &&\
    octez-client --endpoint https://kathmandunet.tezos.marigold.dev config update &&\
    octez-client import secret key oracle_account unencrypted:edskS7XvfNqsdqTiScE764kgBCfCeTBe9sTiZ4TaVTxFpGvMjfWsgDxbo9NZiiZSnWJgGLdZUhRC46B5Wqg7fYfk282TRUd8Gd --force

WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/

CMD [ "/etc/run/sandbox.sh", "-u", "KT1QVV45Rj9r6WbjLczoDxViP9s1JpiCsxVF", "-t", "KT1FRyR3ohQ59N54BJMg9KjDUGh4z5hWuYab", "-b", "KT1NhdYC9f3AUavxuE31BrE3e6hgRiKDoV6g" ]
