version: "2"
services:

  node:
    image: oxheadalpha/flextesa:latest
    hostname: node
    network_mode: "host"
    command: jakartabox start
    ports:
      - 20000:20000
    expose:
      - '20000'
    restart: on-failure
