FROM oxheadalpha/flextesa:20221026

RUN apk update &&\
    apk add bash &&\
    apk add curl &&\
    apk add jq &&\
    octez-client --endpoint https://limanet.tezos.marigold.dev config update &&\
    octez-client import secret key oracle_account unencrypted:edskRheUgunCWW6m5JqoXBjRtxfWDdTjM557uC2TFeLDk4ThfJb5MUDbTagWq1aFjypoQbFjYBRZay1Ujpwg6c9rJcr7RBkBJS --force

WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/

CMD [ "/etc/run/sandbox.sh", "-u", "KT1KK8MyohuuxXDEDuhTqJBUQbxVKJ6PG1Em", "-t", "KT1HiU7EVWwxTFWK4C2DeiwiFYB9GLBDNkP2", "-b", "KT1GUgF7zzN39PZXYqDX9iz2Eo2s5jdNyQ1S" ]
