version: "3"

services:
  batcher-price-ghostnet:
    container_name: price-ghostnet
    build:
      context: .
      dockerfile: Dockerfile.price.ghostnet
    restart: always
  batcher-price-limanet:
    container_name: price-limanet
    build:
      context: .
      dockerfile: Dockerfile.price.limanet
    restart: always
