FROM oxheadalpha/flextesa:latest

RUN apk update &&\
    apk add bash &&\ 
    apk add curl &&\
    apk add jq &&\
    tezos-client --endpoint https://kathmandunet.tezos.marigold.dev config update
    
WORKDIR /etc/run

COPY ./sandbox.sh /etc/run/

CMD [ "/etc/run/sandbox.sh", "-u", "KT1QVV45Rj9r6WbjLczoDxViP9s1JpiCsxVF", "-t", "KT1EGB9ZquErCN3dNvPurmNBuKCAi8pc1ce7", "-b", "KT1FCUp4kN9DziLmiRLMqDnuhBbGSwwoYHD4" ]