name: "Build 0-slip Contracts"
on:
  push: {}
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - run: nix build
    - run: nix flake check
    - name: Store Artefact
      uses: actions/upload-artifact@v2
      with:
          name: batcher-contracts
          path: ./result/*
          retention-days: 1
