name: Docker mainnet

on:
  pull_request:
    branches:
      - 'release-mainnet'
    types:
      - closed

jobs:
  ui:
    strategy:
      matrix:
        network: [mainnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          submodules: true

      - name: Set outputs
        id: vars
        run: |
          echo "date=$(date +%Y-%m-%dT%H-%M-%S)" >> "${GITHUB_OUTPUT}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Set up Docker Buildx
        uses: docker/Setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release version
        if: "github.event.pull_request.merged == true"
        uses: docker/build-push-action@v3
        with:
          file: ./batcher-ui/Dockerfile.${{ matrix.network }}
          context: ./batcher-ui/
          push: true
          tags: |
            ghcr.io/marigold-dev/batcher-${{ matrix.network }}:stable
            ghcr.io/marigold-dev/batcher-${{ matrix.network }}:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}-release
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push release version of notification bot
        uses: docker/build-push-action@v3
        with:
          file: ./batcher-bot/Dockerfile.bot.notifications.${{ matrix.network }}
          context: ./batcher-bot/notifications
          push: true
          tags: |
            ghcr.io/marigold-dev/batcher-bot-notification-${{ matrix.network }}:stable
            ghcr.io/marigold-dev/batcher-bot-notifications-${{ matrix.network }}:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
