name: "Run Breathalyzer Tests"
on:
  push: {}
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - run: make test-batcher
