name: Run Ligo Tests

on:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: Rishabh510/Path-lister-action@master
        with:
          path: "${{ github.workspace }}"
      - name: Run test
        uses: marigold-dev/ligo-action@v0.0.8
        with:
          command: run test ${{ github.workspace }}/batcher/test/test.mligo
