name: "Run Breathalyzer Tests"
on:
  #push: {}
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually

jobs:
  build:
    strategy:
      matrix:
        test:
          - test-batcher
          - test-orders
          - test-math
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: recursive
    - run: make ${{ matrix.test }}
